
import { Program, Mentor, UserProfile } from './types';

// --- MANUALLY INTERLEAVED GLOBAL DATASET ---
const GLOBAL_PROGRAMS_DATA: Program[] = [
    // 1. USA
    {
        id: 'usa_harvard_mba',
        university: 'Harvard Business School',
        programName: 'MBA',
        degreeType: 'MBA',
        specialization: 'General Management',
        country: 'USA',
        city: 'Boston',
        qsRanking: 1,
        tuition: 75000,
        duration: '2 Years',
        acceptanceRate: '10%',
        tags: ['Ivy League', 'Leadership'],
        description: 'The world\'s premier MBA program.',
        fees: { living: 25000, accommodation: 15000, misc: 5000 },
        scholarships: [{ name: 'Merit Based', amount: '$20,000', probability: 'Low' }],
        placements: { medianSalary: 175000, employmentRate: '96%', topEmployers: ['McKinsey', 'Google'] },
        prerequisites: ['GMAT', 'TOEFL'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 2. UK
    {
        id: 'uk_lbs_mba',
        university: 'London Business School',
        programName: 'MBA',
        degreeType: 'MBA',
        specialization: 'Finance',
        country: 'UK',
        city: 'London',
        qsRanking: 5,
        tuition: 85000,
        duration: '18 Months',
        acceptanceRate: '20%',
        tags: ['Finance', 'City'],
        description: 'Top ranked MBA in London.',
        fees: { living: 25000, accommodation: 15000, misc: 5000 },
        scholarships: [],
        placements: { medianSalary: 120000, employmentRate: '95%', topEmployers: ['McKinsey', 'Goldman'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'Medium',
        accommodationOptions: ['Off-campus']
    },
    // 3. Canada
    {
        id: 'can_rotman_mba',
        university: 'Rotman School of Management',
        programName: 'MBA',
        degreeType: 'MBA',
        specialization: 'Finance',
        country: 'Canada',
        city: 'Toronto',
        qsRanking: 40,
        tuition: 60000,
        duration: '2 Years',
        acceptanceRate: '35%',
        tags: ['Finance', 'Canada'],
        description: '#1 Business School in Canada.',
        fees: { living: 18000, accommodation: 12000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 95000, employmentRate: '92%', topEmployers: ['RBC', 'TD'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 4. Germany
    {
        id: 'ger_tum_ms_ds',
        university: 'Technical University of Munich',
        programName: 'MSc Data Engineering',
        degreeType: 'MS',
        specialization: 'Data Science',
        country: 'Germany',
        city: 'Munich',
        qsRanking: 28,
        tuition: 3000,
        duration: '2 Years',
        acceptanceRate: '15%',
        tags: ['Tech', 'Engineering'],
        description: 'Top ranked German technical university.',
        fees: { living: 12000, accommodation: 8000, misc: 1000 },
        scholarships: [],
        placements: { medianSalary: 65000, employmentRate: '92%', topEmployers: ['BMW', 'Siemens'] },
        prerequisites: ['GRE', 'IELTS'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 5. Singapore
    {
        id: 'sin_nus_ms_ba',
        university: 'National University of Singapore',
        programName: 'MS Business Analytics',
        degreeType: 'MS',
        specialization: 'Data Science',
        country: 'Singapore',
        city: 'Singapore',
        qsRanking: 8,
        tuition: 45000,
        duration: '1 Year',
        acceptanceRate: '15%',
        tags: ['Asia', 'Analytics'],
        description: 'Top analytics program in Asia.',
        fees: { living: 15000, accommodation: 10000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 70000, employmentRate: '95%', topEmployers: ['Grab', 'Shopee'] },
        prerequisites: ['GRE'],
        interviewRequired: true,
        citySafetyScore: 'Very High',
        accommodationOptions: ['On-campus']
    },
    // 6. Australia
    {
        id: 'aus_melb_bba',
        university: 'University of Melbourne',
        programName: 'Bachelor of Commerce',
        degreeType: 'Undergraduate',
        specialization: 'Business',
        country: 'Australia',
        city: 'Melbourne',
        qsRanking: 14,
        tuition: 32000,
        duration: '3 Years',
        acceptanceRate: '30%',
        tags: ['Commerce', 'Group of 8'],
        description: 'Leading undergraduate business degree.',
        fees: { living: 18000, accommodation: 12000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 55000, employmentRate: '90%', topEmployers: ['Big 4'] },
        prerequisites: ['IELTS'],
        interviewRequired: false,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 7. India
    {
        id: 'ind_isb_mba',
        university: 'Indian School of Business (ISB)',
        programName: 'PGP in Management',
        degreeType: 'MBA',
        specialization: 'Management',
        country: 'India',
        city: 'Hyderabad',
        qsRanking: 32,
        tuition: 35000,
        duration: '1 Year',
        acceptanceRate: '18%',
        tags: ['India', 'Business'],
        description: 'A globally top-ranked business school in India.',
        fees: { living: 5000, accommodation: 3000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 40000, employmentRate: '99%', topEmployers: ['McKinsey', 'Google'] },
        prerequisites: ['GMAT', 'GRE'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 8. France
    {
        id: 'fra_insead_mba',
        university: 'INSEAD',
        programName: 'MBA',
        degreeType: 'MBA',
        specialization: 'International Business',
        country: 'France',
        city: 'Fontainebleau',
        qsRanking: 2,
        tuition: 90000,
        duration: '1 Year',
        acceptanceRate: '30%',
        tags: ['Global', 'Consulting'],
        description: 'The Business School for the World.',
        fees: { living: 15000, accommodation: 10000, misc: 3000 },
        scholarships: [],
        placements: { medianSalary: 115000, employmentRate: '94%', topEmployers: ['MBB'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 9. USA
    {
        id: 'usa_cmu_ms_cs',
        university: 'Carnegie Mellon University',
        programName: 'MS in Computer Science',
        degreeType: 'MS',
        specialization: 'Computer Science',
        country: 'USA',
        city: 'Pittsburgh',
        qsRanking: 3,
        tuition: 55000,
        duration: '1.5 Years',
        acceptanceRate: '5%',
        tags: ['AI', 'Robotics'],
        description: 'Top-ranked CS program globally.',
        fees: { living: 15000, accommodation: 12000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 140000, employmentRate: '98%', topEmployers: ['Google', 'Meta'] },
        prerequisites: ['GRE'],
        interviewRequired: false,
        citySafetyScore: 'Medium',
        accommodationOptions: ['Off-campus']
    },
    // 10. UK
    {
        id: 'uk_oxford_mba',
        university: 'University of Oxford',
        programName: 'MBA',
        degreeType: 'MBA',
        specialization: 'Management',
        country: 'UK',
        city: 'Oxford',
        qsRanking: 4,
        tuition: 75000,
        duration: '1 Year',
        acceptanceRate: '15%',
        tags: ['Prestige', 'History'],
        description: 'World-class business education.',
        fees: { living: 18000, accommodation: 12000, misc: 3000 },
        scholarships: [],
        placements: { medianSalary: 110000, employmentRate: '93%', topEmployers: ['Finance', 'Consulting'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['College']
    },
    // 11. Canada
    {
        id: 'can_ubc_ms_ds',
        university: 'University of British Columbia',
        programName: 'Master of Data Science',
        degreeType: 'MS',
        specialization: 'Data Science',
        country: 'Canada',
        city: 'Vancouver',
        qsRanking: 35,
        tuition: 40000,
        duration: '10 Months',
        acceptanceRate: '15%',
        tags: ['Tech', 'West Coast'],
        description: 'Accelerated professional data science degree.',
        fees: { living: 20000, accommodation: 15000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 85000, employmentRate: '95%', topEmployers: ['Amazon', 'Microsoft'] },
        prerequisites: ['IELTS'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 12. Germany
    {
        id: 'ger_rwth_ms_mech',
        university: 'RWTH Aachen',
        programName: 'MSc Mechanical Engineering',
        degreeType: 'MS',
        specialization: 'Engineering',
        country: 'Germany',
        city: 'Aachen',
        qsRanking: 55,
        tuition: 1000,
        duration: '2 Years',
        acceptanceRate: '20%',
        tags: ['Engineering', 'Automotive'],
        description: 'Leading mechanical engineering school.',
        fees: { living: 10000, accommodation: 6000, misc: 1000 },
        scholarships: [],
        placements: { medianSalary: 60000, employmentRate: '94%', topEmployers: ['Porsche', 'Bosch'] },
        prerequisites: ['German B1'],
        interviewRequired: false,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 13. Singapore
    {
        id: 'sin_ntu_mba',
        university: 'Nanyang Technological University',
        programName: 'Nanyang MBA',
        degreeType: 'MBA',
        specialization: 'General Management',
        country: 'Singapore',
        city: 'Singapore',
        qsRanking: 25,
        tuition: 50000,
        duration: '1 Year',
        acceptanceRate: '20%',
        tags: ['MBA', 'Asia'],
        description: 'Focus on Asian business leadership.',
        fees: { living: 15000, accommodation: 10000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 80000, employmentRate: '96%', topEmployers: ['Tech', 'Finance'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'Very High',
        accommodationOptions: ['On-campus']
    },
    // 14. India
    {
        id: 'ind_iitb_ug_cs',
        university: 'IIT Bombay',
        programName: 'B.Tech Computer Science',
        degreeType: 'Undergraduate',
        specialization: 'Computer Science',
        country: 'India',
        city: 'Mumbai',
        qsRanking: 149,
        tuition: 4000,
        duration: '4 Years',
        acceptanceRate: '1%',
        tags: ['Engineering', 'Elite'],
        description: 'Most prestigious engineering program in India.',
        fees: { living: 3000, accommodation: 1000, misc: 500 },
        scholarships: [],
        placements: { medianSalary: 35000, employmentRate: '100%', topEmployers: ['HFTs', 'Big Tech'] },
        prerequisites: ['JEE Advanced'],
        interviewRequired: false,
        citySafetyScore: 'Medium',
        accommodationOptions: ['On-campus']
    },
    // 15. USA
    {
        id: 'usa_columbia_ms_fin',
        university: 'Columbia University',
        programName: 'MS in Financial Engineering',
        degreeType: 'MS',
        specialization: 'Finance',
        country: 'USA',
        city: 'New York',
        qsRanking: 10,
        tuition: 70000,
        duration: '1.5 Years',
        acceptanceRate: '12%',
        tags: ['Wall Street', 'Finance'],
        description: 'Direct pipeline to NYC finance jobs.',
        fees: { living: 30000, accommodation: 20000, misc: 5000 },
        scholarships: [],
        placements: { medianSalary: 150000, employmentRate: '95%', topEmployers: ['Goldman Sachs', 'JPM'] },
        prerequisites: ['GRE'],
        interviewRequired: true,
        citySafetyScore: 'Medium',
        accommodationOptions: ['Off-campus']
    },
    // 16. UK
    {
        id: 'uk_imperial_msc_cs',
        university: 'Imperial College London',
        programName: 'MSc Computing',
        degreeType: 'MS',
        specialization: 'Computer Science',
        country: 'UK',
        city: 'London',
        qsRanking: 7,
        tuition: 45000,
        duration: '1 Year',
        acceptanceRate: '10%',
        tags: ['Tech', 'Innovation'],
        description: 'Specialized computing program.',
        fees: { living: 25000, accommodation: 15000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 70000, employmentRate: '96%', topEmployers: ['Google', 'DeepMind'] },
        prerequisites: ['GRE'],
        interviewRequired: false,
        citySafetyScore: 'Medium',
        accommodationOptions: ['Off-campus']
    },
    // 17. Australia
    {
        id: 'aus_syd_ms_fin',
        university: 'University of Sydney',
        programName: 'Master of Commerce (Finance)',
        degreeType: 'MS',
        specialization: 'Finance',
        country: 'Australia',
        city: 'Sydney',
        qsRanking: 19,
        tuition: 35000,
        duration: '1.5 Years',
        acceptanceRate: '35%',
        tags: ['Finance', 'Sydney'],
        description: 'Flexible masters program.',
        fees: { living: 20000, accommodation: 15000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 70000, employmentRate: '92%', topEmployers: ['Banks'] },
        prerequisites: ['IELTS'],
        interviewRequired: false,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 18. Switzerland
    {
        id: 'swi_eth_ms_cs',
        university: 'ETH Zurich',
        programName: 'MSc Computer Science',
        degreeType: 'MS',
        specialization: 'Computer Science',
        country: 'Switzerland',
        city: 'Zurich',
        qsRanking: 7,
        tuition: 1500,
        duration: '2 Years',
        acceptanceRate: '20%',
        tags: ['Tech', 'Europe'],
        description: 'World renowned technical institute.',
        fees: { living: 20000, accommodation: 12000, misc: 3000 },
        scholarships: [],
        placements: { medianSalary: 100000, employmentRate: '95%', topEmployers: ['Google Zurich'] },
        prerequisites: ['GRE'],
        interviewRequired: false,
        citySafetyScore: 'Very High',
        accommodationOptions: ['Off-campus']
    },
    // 19. USA
    {
        id: 'usa_stanford_mba',
        university: 'Stanford GSB',
        programName: 'MBA',
        degreeType: 'MBA',
        specialization: 'Entrepreneurship',
        country: 'USA',
        city: 'Stanford',
        qsRanking: 2,
        tuition: 78000,
        duration: '2 Years',
        acceptanceRate: '6%',
        tags: ['Silicon Valley', 'Tech'],
        description: 'Located in the heart of Silicon Valley.',
        fees: { living: 28000, accommodation: 18000, misc: 5000 },
        scholarships: [],
        placements: { medianSalary: 180000, employmentRate: '94%', topEmployers: ['VC Firms', 'Tech Giants'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 20. India
    {
        id: 'ind_ashoka_ug',
        university: 'Ashoka University',
        programName: 'BA Economics & Finance',
        degreeType: 'Undergraduate',
        specialization: 'Economics',
        country: 'India',
        city: 'Sonipat',
        qsRanking: 800,
        tuition: 12000,
        duration: '3 Years',
        acceptanceRate: '10%',
        tags: ['Liberal Arts'],
        description: 'Pioneering liberal arts education in India.',
        fees: { living: 4000, accommodation: 4000, misc: 1000 },
        scholarships: [],
        placements: { medianSalary: 15000, employmentRate: '90%', topEmployers: ['Consulting'] },
        prerequisites: ['SAT/AAT'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 21. Netherlands
    {
        id: 'ned_delft_ms_design',
        university: 'TU Delft',
        programName: 'MSc Integrated Product Design',
        degreeType: 'MS',
        specialization: 'Design',
        country: 'Netherlands',
        city: 'Delft',
        qsRanking: 50,
        tuition: 18000,
        duration: '2 Years',
        acceptanceRate: '25%',
        tags: ['Design', 'Innovation'],
        description: 'Leading design and engineering program.',
        fees: { living: 12000, accommodation: 8000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 55000, employmentRate: '90%', topEmployers: ['Philips', 'ASML'] },
        prerequisites: ['Portfolio'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 22. USA
    {
        id: 'usa_mit_ms_ba',
        university: 'MIT Sloan',
        programName: 'Master of Business Analytics',
        degreeType: 'MS',
        specialization: 'Data Science',
        country: 'USA',
        city: 'Cambridge',
        qsRanking: 1,
        tuition: 85000,
        duration: '1 Year',
        acceptanceRate: '8%',
        tags: ['Analytics', 'Quant'],
        description: 'Rigorous analytics program.',
        fees: { living: 25000, accommodation: 18000, misc: 3000 },
        scholarships: [],
        placements: { medianSalary: 130000, employmentRate: '99%', topEmployers: ['BCG Gamma', 'Amazon'] },
        prerequisites: ['GRE'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 23. Ireland
    {
        id: 'ire_tcd_ms_cs',
        university: 'Trinity College Dublin',
        programName: 'MSc Computer Science',
        degreeType: 'MS',
        specialization: 'Computer Science',
        country: 'Ireland',
        city: 'Dublin',
        qsRanking: 90,
        tuition: 25000,
        duration: '1 Year',
        acceptanceRate: '30%',
        tags: ['Tech', 'Europe'],
        description: 'Oldest university in Ireland.',
        fees: { living: 15000, accommodation: 12000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 60000, employmentRate: '92%', topEmployers: ['Google Dublin', 'Meta'] },
        prerequisites: ['IELTS'],
        interviewRequired: false,
        citySafetyScore: 'High',
        accommodationOptions: ['On-campus']
    },
    // 24. Spain
    {
        id: 'esp_ie_mim',
        university: 'IE Business School',
        programName: 'Master in Management',
        degreeType: 'MiM',
        specialization: 'Management',
        country: 'Spain',
        city: 'Madrid',
        qsRanking: 25,
        tuition: 40000,
        duration: '1 Year',
        acceptanceRate: '30%',
        tags: ['Entrepreneurship'],
        description: 'Innovative business school in Madrid.',
        fees: { living: 15000, accommodation: 10000, misc: 2000 },
        scholarships: [],
        placements: { medianSalary: 65000, employmentRate: '91%', topEmployers: ['Tech', 'Consulting'] },
        prerequisites: ['GMAT'],
        interviewRequired: true,
        citySafetyScore: 'High',
        accommodationOptions: ['Off-campus']
    },
    // 25. India
    {
        id: 'ind_nmims_bba',
        university: 'NMIMS',
        programName: 'BBA',
        degreeType: 'Undergraduate',
        specialization: 'Business',
        country: 'India',
        city: 'Mumbai',
        qsRanking: 700,
        tuition: 5000,
        duration: '3 Years',
        acceptanceRate: '25%',
        tags: ['Management'],
        description: 'Top private B-school for undergrads.',
        fees: { living: 5000, accommodation: 3000, misc: 1000 },
        scholarships: [],
        placements: { medianSalary: 8000, employmentRate: '85%', topEmployers: ['Finance', 'Marketing'] },
        prerequisites: ['NPAT'],
        interviewRequired: false,
        citySafetyScore: 'Medium',
        accommodationOptions: ['Off-campus']
    },
    // 26. USA
    {
        id: 'usa_nyu_ug_econ',
        university: 'NYU',
        programName: 'BA in Economics',
        degreeType: 'Undergraduate',
        specialization: 'Economics',
        country: 'USA',
        city: 'New York',
        qsRanking: 25,
        tuition: 60000,
        duration: '4 Years',
        acceptanceRate: '15%',
        tags: ['Urban', 'Global'],
        description: 'Study economics in the financial capital of the world.',
        fees: { living: 30000, accommodation: 20000, misc: 4000 },
        scholarships: [],
        placements: { medianSalary: 80000, employmentRate: '92%', topEmployers: ['Banks', 'Consulting'] },
        prerequisites: ['SAT'],
        interviewRequired: false,
        citySafetyScore: 'Medium',
        accommodationOptions: ['On-campus']
    }
];

export const MOCK_PROGRAMS: Program[] = GLOBAL_PROGRAMS_DATA;

export const MOCK_MENTORS: Mentor[] = [
  {
    id: 'm1',
    name: 'Sarah Jenkins',
    title: 'Ex-Admissions Officer at Stanford',
    specialties: ['Ivy League', 'Essay Strategy', 'Interview Prep'],
    imageUrl: 'https://picsum.photos/200/200?random=1',
    category: 'Study Abroad',
    rate: '$150/hr',
    bio: 'I spent 5 years reading applications at Stanford. I know exactly what gets an application moved from the "maybe" pile to the "admit" pile.',
    experienceYears: 8,
    reviews: [
      { id: 'r1', author: 'Mike T.', rating: 5, text: 'Sarah completely transformed my SOP!' }
    ],
    availability: ['Mon 10:00 AM', 'Tue 2:00 PM', 'Fri 9:00 AM']
  },
  {
    id: 'm2',
    name: 'David Chen',
    title: 'Senior Essay Editor',
    specialties: ['Storytelling', 'Creative Writing', 'Harvard SOPs'],
    imageUrl: 'https://picsum.photos/200/200?random=2',
    category: 'Essay',
    rate: '$90/hr',
    bio: 'Professional editor with a background in creative writing. I help you find your unique voice.',
    experienceYears: 5,
    reviews: [
      { id: 'r2', author: 'Lisa M.', rating: 5, text: 'The best investment I made for my application.' }
    ],
    availability: ['Wed 1:00 PM', 'Thu 4:00 PM']
  },
  {
    id: 'm3',
    name: 'Dr. Emily Al-Fayed',
    title: 'Financial Aid Consultant',
    specialties: ['Scholarships', 'Loans', 'Budgeting'],
    imageUrl: 'https://picsum.photos/200/200?random=3',
    category: 'Finance',
    rate: '$120/hr',
    bio: 'Helping students navigate the complex world of study abroad financing and scholarships.',
    experienceYears: 10,
    reviews: [],
    availability: ['Mon 11:00 AM', 'Wed 10:00 AM']
  },
  {
    id: 'm4',
    name: 'Raj Patel',
    title: 'Tech Resume Expert',
    specialties: ['CS Resumes', 'FAANG Recruiters', 'ATS Optimization'],
    imageUrl: 'https://picsum.photos/200/200?random=4',
    category: 'Resume',
    rate: '$80/hr',
    bio: 'Ex-Google recruiter who knows exactly what technical hiring managers look for.',
    experienceYears: 6,
    reviews: [],
    availability: ['Tue 6:00 PM', 'Sat 11:00 AM']
  }
];

// STRICT RESET: INITIAL_PROFILE MUST BE EMPTY
// This ensures no "Alex Student" exists by default.
export const INITIAL_PROFILE: UserProfile = {
  name: '',
  email: '',
  degreeType: '',
  targetMajor: '',
  gpa: '',
  testStatus: '',
  budget: '',
  countries: [],
  experienceYears: 0,
  savedShortlist: [], // Added to match updated UserProfile interface
  education: [],
  tests: [],
  workExperience: [],
  activities: []
};